#ifndef IEC_VAR_H
#define IEC_VAR_H

enum IEC_TYPE_VAR
{
    IEC_TYPE_BOOL,
    IEC_TYPE_BYTE,
    IEC_TYPE_DATE,
    IEC_TYPE_DINT,
    IEC_TYPE_DT,
    IEC_TYPE_DWORD,
    IEC_TYPE_INT,
    IEC_TYPE_LINT,
    IEC_TYPE_LREAL, IEC_TYPE_LWORD,
    IEC_TYPE_REAL,
    IEC_TYPE_SINT,
    IEC_TYPE_STRING,
    IEC_TYPE_TIME,
    IEC_TYPE_TOD,
    IEC_TYPE_UDINT,
    IEC_TYPE_UINT,
    IEC_TYPE_ULINT,
    IEC_TYPE_USINT,
    IEC_TYPE_WORD
} ;

#endif
